# Generated by Django 5.0 on 2024-08-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_email_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("first_name",),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
