# Generated by Django 5.0 on 2024-09-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
