# Generated by Django 5.0 on 2024-09-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_userprofile_avatar_userprofile_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="ProxyUser",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
