# Generated by Django 5.0 on 2024-10-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_proxyuser_userprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="Profile",
        ),
    ]
