# Generated by Django 5.0 on 2024-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_books_options_alter_books_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="author",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="books",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
