# Generated by Django 5.0 on 2024-08-29 06:29

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_books_author_alter_books_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="price",
            field=models.DecimalField(decimal_places=2, default="exit", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="books",
            name="quantity",
            field=models.PositiveIntegerField(default="exit"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="books",
            name="total_quantity",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("quantity"), "*", models.F("price")
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=10),
            ),
        ),
    ]
