# Generated by Django 5.0 on 2024-09-18 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0002_rename_subscriber_cost_subscription_subscription_cost_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Basic",
            fields=[
                (
                    "subscription_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="subscriptions.subscription",
                    ),
                ),
                ("thumbnail_photo_200px", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Basic Subscription",
                "verbose_name_plural": "Basic Subscriptions",
            },
            bases=("subscriptions.subscription",),
        ),
        migrations.CreateModel(
            name="Premium",
            fields=[
                (
                    "basic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="subscriptions.basic",
                    ),
                ),
                ("thumbnail_photo_400px", models.BooleanField(default=True)),
                ("original_photo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Premium Subscription",
                "verbose_name_plural": "Premium Subscriptions",
            },
            bases=("subscriptions.basic",),
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "premium_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="subscriptions.premium",
                    ),
                ),
                ("binary_link", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Enterprise Subscription",
                "verbose_name_plural": "Enterprise Subscriptions",
            },
            bases=("subscriptions.premium",),
        ),
    ]
