# Generated by Django 5.0 on 2024-09-18 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basic",
            name="thumbnail_photo_200px",
            field=models.BooleanField(
                default=True, validators=[django.core.validators.MinValueValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="binary_link",
            field=models.CharField(
                max_length=255, validators=[django.core.validators.MinValueValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="premium",
            name="original_photo",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="premium",
            name="thumbnail_photo_400px",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
    ]
