version: "3"

services:
  backend:
    build: ./
    container_name: assignment_container
    working_dir: /assignment
    command:
      - ./commands/start_server_${MODE}.sh
    ports:
        - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
        - ./src:/assignment/src
        - ./commands:/assignment/commands
    env_file:
        - .env
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false

  grafana:
    container_name: grafana_container
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'

volumes:
  esdata1:
  grafana_data:
  prometheus_data: